<a href="https://colab.research.google.com/github/EzraLimyz/Entregues/blob/main/Entrega1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

1. Donades les següents matrius:

In [ ]:
import numpy as np

In [ ]:
A=np.array([[1,2,0],[0,2,0],[0,0,3]])
print(A)

[[1 2 0]
 [0 2 0]
 [0 0 3]]


In [ ]:
B=np.array([[3,1,0],[0,2,0],[0,0,4]])
print(B)

[[3 1 0]
 [0 2 0]
 [0 0 4]]


In [ ]:
C=np.array([[2,0,0],[0,-1,1],[0,0,3]])
print(C)

[[ 2  0  0]
 [ 0 -1  1]
 [ 0  0  3]]


a) Calcula 3A+2B i (A+B)C

In [ ]:
print(3*A+2*B)

[[ 9  8  0]
 [ 0 10  0]
 [ 0  0 17]]


In [ ]:
print((A+B)*C)

[[ 8  0  0]
 [ 0 -4  0]
 [ 0  0 21]]


b) Diagonalitza les matrius i calcula els valors i vectors propis.

In [ ]:
Valors, Vectors = np.linalg.eig(A)
print(Valors)
print(Vectors)

[1. 2. 3.]
[[1.         0.89442719 0.        ]
 [0.         0.4472136  0.        ]
 [0.         0.         1.        ]]


In [ ]:
Valors, Vectors = np.linalg.eig(B)
print(Valors)
print(Vectors)

[3. 2. 4.]
[[ 1.         -0.70710678  0.        ]
 [ 0.          0.70710678  0.        ]
 [ 0.          0.          1.        ]]


In [ ]:
Valors, Vectors = np.linalg.eig(C)
print(Valors)
print(Vectors)

[ 2. -1.  3.]
[[1.         0.         0.        ]
 [0.         1.         0.24253563]
 [0.         0.         0.9701425 ]]
